WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37dfdbc550>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37dfdbcc18>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37dfdbcdd8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37dfdbcf28>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02ae0b8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02ccf60>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cd128>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cd278>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cd3c8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cd550>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cde10>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cdf98>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e025c0f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e025c278>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f37e02cd588>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f44a431ff60>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/fastparquet/
slurmstepd: error: *** JOB 444194 ON cnx027 CANCELLED AT 2025-06-01T21:28:49 DUE TO TIME LIMIT ***
