WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736266780>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736209240>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736209390>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7362094e0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736209630>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736209438>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736238f28>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7362420f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736242278>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736242400>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736242cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736242e48>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe736242f60>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe735b9f128>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe735b9f2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/wheel/
slurmstepd: error: *** JOB 447145 ON cnx001 CANCELLED AT 2025-06-05T12:34:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 447145 STEPD TERMINATED ON cnx001 AT 2025-06-05T12:35:31 DUE TO JOB NOT ENDING WITH SIGNALS ***
slurmstepd: error: Container 310920 in cgroup plugin has 1 processes, giving up after 63 sec
